- name: Flush iptables filter
  command: iptables -F

- name: Flush iptables nat
  command: iptables -t nat -F

- name: Stop iptables
  service: name=iptables
           enabled=no
           state=stopped
  ignore_errors: yes

- name: Stop firewalld
  service: name=firewalld
           enabled=no
           state=stopped
  ignore_errors: yes

- name: Stop NetworkManager
  service: name=NetworkManager
           enabled=no
           state=stopped
  ignore_errors: yes

- name: Disable SELinux
  selinux: conf=/etc/sysconfig/selinux
           policy=targeted
           state=disabled
