---
# Variables listed here are application to mesos zookeeper hosts.
ZK_MAXCLIENTCNXNS: 50
ZK_TICKTIME: 2000
ZK_INITLIMIT: 10
ZK_SYNCLIMIT: 5
ZK_DATADIR: /var/lib/zookeeper
ZK_CLIENTPORT: 2181
ZK_SERVER_1: server.1={{ SERVER_1 }}:2888:3888
ZK_SERVER_2: server.2={{ SERVER_2 }}:2888:3888
ZK_SERVER_1_MYID: 1
ZK_SERVER_2_MYID: 2

# Variables listed here are application to mesos hosts.
MESOS_ZK_ADDRESS: "{{ SERVER_1 }}:2181,{{ SERVER_2 }}:2181"
MESOS_CLUSTER_NAME: MyCluster1
MESOS_QUORUM: 1
MESOS_WORK_DIR: /var/lib/mesos
MESOS_HOSTNAME: "{{ ansible_default_ipv4.address }}"

# Variables listed here are application to marathon hosts.
MARATHON_HOSTNAME: "{{ ansible_default_ipv4.address }}"
MARATHON_MASTER: "{{ SERVER_1 }}:2181,{{ SERVER_2 }}:2181"
MARATHON_ZK: "{{ SERVER_1 }}:2181,{{ SERVER_2 }}:2181"
