---
- name: Apply configuration to common nodes
  hosts: all
  roles:
    - common

- name: Apply configuration to mesos_master nodes
  hosts: mesos_master
  roles:
    - mesos_master

- name: Apply configuration to mesos_slave nodes
  hosts: mesos_slave
  roles:
    - mesos_slave

- name: Apply configuration to harbor nodes
  hosts: harbor
  roles:
    - harbor
