---
# Variables listed here are application to etcd hosts.
ETCD_INSTALL_PATH: /usr/local/src
ETCD_DOWNLOAD_URL: https://github.com/coreos/etcd/releases/download/v3.0.10/etcd-v3.0.10-linux-amd64.tar.gz
ETCD_TAR_FILE_NAME: etcd-v3.0.10-linux-amd64.tar.gz
ETCD_FILE_NAME: etcd-v3.0.10-linux-amd64

# Variables listed here are application to calicoctl hosts.
CALICO_INSTALL_PATH: /usr/bin
CALICO_DOWNLOAD_URL: http://www.projectcalico.org/builds/calicoctl
CALICO_FILE_NAME: calicoctl

# Variables listed here are application to docker.service
DOCKER_DAEMON_TCP: tcp://0.0.0.0:2375
DOCKER_CLUSTER_STORE: etcd://172.30.16.122:2379
DOCKER_CLUSTER_ADVERTISE: "{{ ansible_default_ipv4.address }}:2375"
DOCKER_INSECURE_REGISTRY: "{{ ansible_default_ipv4.address }}:80"
